parameters:
    env(OAUTH_CLIENT): ''
    env(OAUTH_SECRET): ''
    env(OAUTH_USERNAME): ''
    env(OAUTH_PASSWORD): ''
    env(OAUTH_URL): ''

eight_points_guzzle:
    clients:
        api_title:
            base_url: '%env(resolve:OAUTH_URL)%'

            # Write here the host where to do requests
            # base_url: "http://target.url"

            options:
                auth: oauth2

                # Configure headers.
                # More info: http://docs.guzzlephp.org/en/stable/request-options.html#headers
                headers:
                    User-Agent: "EightpointsGuzzleBundle/7.0"

            # Find plugins here:
            # https://github.com/8p/EightPointsGuzzleBundle#known-and-supported-plugins
            plugin:
                oauth2:
                    base_uri:       '%env(resolve:OAUTH_URL)%'
                    token_url:      "/oauth/v2/token"
                    client_id:      '%env(resolve:OAUTH_CLIENT)%'
                    client_secret:  '%env(resolve:OAUTH_SECRET)%'
                    username:       '%env(resolve:OAUTH_USERNAME)%'
                    password:       '%env(resolve:OAUTH_PASSWORD)%'
                    scope:          "scope1"
                    grant_type:     "Sainsburys\\Guzzle\\Oauth2\\GrantType\\PasswordCredentials"
