#index:
#    path: /
#    controller: App\Controller\DefaultController::index

home_page:
    path:         /
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: home.html.twig



fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"